// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qsmibejovsebbqropwfr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFzbWliZWpvdnNlYmJxcm9wd2ZyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1ODg2NzEsImV4cCI6MjA2NDE2NDY3MX0.XgWyQ2Wdpr-JV-xWoermLmFyq7v2eEUDDr1kEaZKOmM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);